on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install HubSpot CLI
        run: npm install -g @hubspot/cli

      - name: Prepare HubSpot config
        run: |
          sed "s/ACCOUNT_ID_PLACEHOLDER/${{ vars.HUBSPOT_ACCOUNT_ID }}/g; s/ACCESS_KEY_PLACEHOLDER/${{ secrets.HUBSPOT_PERSONAL_ACCESS_KEY }}/g" hubspot.config.ci.yml > hubspot.config.yml

      - name: Deploy to HubSpot
        run: npx hs upload galeriemauritiushof galeriemauritiushof --account 7913768

