on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to HubSpot CMS
        uses: HubSpot/cms-deploy-action@v2.3.2

        with:
          src_dir: galeriemauritiushof
          dest_dir: galeriemauritiushof
          account_id: ${{ vars.HUBSPOT_ACCOUNT_ID }}
          personal_access_key: ${{ secrets.HUBSPOT_PERSONAL_ACCESS_KEY }}
